[package]
name = "caper"
version = "0.10.0"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shockham/caper"
homepage = "https://github.com/shockham/caper"
documentation = "https://docs.rs/caper/*/caper/"
description = "Minimalist game framework"

[dependencies]
glium = "0.21"
glium_text_rusttype = { git = "https://github.com/shockham/glium_text", branch = "rusttype" }#"0.3.1"
time = "0.1"
genmesh = "0.5"
obj = { version = "0.8", features = ["genmesh"] }
noise = "0.5"
imgui = { git = "https://github.com/Gekkio/imgui-rs" }#"0.0.18"
imgui-glium-renderer = { git = "https://github.com/Gekkio/imgui-rs" }#"0.0.18"
fps_counter = "1.0.0"
bincode = "1.0"
serde = "1.0"
serde_derive = "1.0"
nphysics3d = "0.8"
nalgebra = "0.14"
ncollide3d = "0.15"
image = "0.19"
gif = "0.10"
derive_builder = "0.5"
lazy_static = "1.0"
rayon = "1.0"
volition = "0.0.16"
impose = "0.2"
