[package]
name = "caper"
version = "0.6.1"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shockham/caper"
homepage = "https://github.com/shockham/caper"
documentation = "https://docs.rs/caper/*/caper/"
description = "Small game framework"

[dependencies]
glium = "0.16"
glium_text_rusttype = "0.1.0"
time = "0.1"
genmesh = "0.5"
obj = { version = "0.7", features = ["genmesh"] }
noise = "0.4"
imgui = "0.0.13"
imgui-glium-renderer = "0.0.13"
fps_counter = "0.2.0"
bincode = "0.8"
serde = "1.0"
serde_derive = "1.0"
nphysics3d = "0.6"
nalgebra = "0.11"
ncollide = "0.11"
image = "0.14"
gif = "0.9"
derive_builder = "0.5"
rodio = "0.5"
lazy_static = "0.2"
rayon = "0.8"
