[package]
name = "caper"
version = "0.9.0"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shockham/caper"
homepage = "https://github.com/shockham/caper"
documentation = "https://docs.rs/caper/*/caper/"
description = "Minimalist game framework"

[dependencies]
glium = "0.17"
glium_text_rusttype = "0.2.0"
time = "0.1"
genmesh = "0.5"
obj = { version = "0.8", features = ["genmesh"] }
noise = "0.4"
imgui = "0.0.15"
imgui-glium-renderer = "0.0.15"
fps_counter = "1.0.0"
bincode = "0.9"
serde = "1.0"
serde_derive = "1.0"
nphysics3d = "0.7"
nalgebra = "0.13"
ncollide = "0.13"
image = "0.17"
gif = "0.9"
derive_builder = "0.5"
lazy_static = "0.2"
rayon = "0.8"
volition = "0.0.7"
impose = "0.1.0"
