[package]
name = "caper"
version = "0.1.8"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shockham/caper"
homepage = "https://github.com/shockham/caper"
documentation = "https://docs.rs/caper/*/caper/"
description = "Small game framework"

[dependencies]
glium = "0.16"
glium_text = "0.11"
time = "0.1"
genmesh = "0.4"
obj = { version = "0.5", features = ["usegenmesh"] }
noise = "0.2"
imgui = "0.0.11" 
fps_counter = "0.2.0"
bincode = "0.6"
rustc-serialize = "0.3"
nphysics3d = "0.6"
nalgebra = "0.11"
ncollide = "0.11"
image = "0.12"
gif = "0.9"
derive_builder = "0.4"
